### ISSUE TITLE
Using with styles from node-modules

### ISSUE THREAD

**Issue by Stalso** [dferber90/fake-style-loader#2]
Hello. I am trying to use this loader in project based on [this awesome template](https://github.com/mxstbr/react-boilerplate). I am trying to implement ssr in it. For this purpose I need server webpack  bundle. I have made the following config file for webpack:

```
const path = require('path');
const webpack = require('webpack');
var ExternalsPlugin = require('webpack-externals-plugin');

// // PostCSS plugins
const cssnext = require('postcss-cssnext');
const postcssFocus = require('postcss-focus');
const postcssReporter = require('postcss-reporter');

module.exports = {
  entry: path.join(process.cwd(), 'server/index.js'),

  output: { // Compile into js/build.js
    path: path.resolve(process.cwd(), 'build'),
    publicPath: '/',
    libraryTarget : 'commonjs2',
    pathinfo: true,
    filename: 'server.js',
  }, // Merge with env dependent settings

  module: {
    loaders: [{
      test: /\.js$/, // Transform all .js files required somewhere with Babel
      loader: 'babel',
      exclude: /node_modules/,

    }, {
        // Transform our own .css files with PostCSS and CSS-modules
        test: /\.css$/,
        exclude: /node_modules/,
        loader: 'fake-style-loader!css-loader?localIdentName=[local]__[path][name]__[hash:base64:5]&modules&importLoaders=1&sourceMap!postcss-loader',
      }, {

        test: /\.css$/,
        include: /node_modules/,
        loader: 'fake-style-loader!css-loader?modules',
      }, {
        test: /\.(eot|svg|ttf|woff|woff2)$/,
        loader: 'file-loader',
      }, {
        test: /\.(jpg|png|gif)$/,
        loaders: [
          'file-loader',
          'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}',
        ],
      }, {
        test: /\.html$/,
        loader: 'html-loader',
      }, {
        test: /\.json$/,
        loader: 'json-loader',
      }, {
        test: /\.(mp4|webm)$/,
        loader: 'url-loader?limit=10000',
      }],
  },
  devtool: 'source-map',
  plugins: [

    new webpack.ProvidePlugin({
      // make fetch available
      fetch: 'exports?self.fetch!whatwg-fetch',
    }),
    new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 }),
    // Always expose NODE_ENV to webpack, in order to use `process.env.NODE_ENV`
    // inside your code for any environment checks; UglifyJS will automatically
    // drop any unreachable code.
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),

      },
      __CLIENT__: false,
      __SERVER__: true
    })
    ,
    new ExternalsPlugin({
      type: 'commonjs2',
      exclude: path.join(process.cwd(), 'node_modules/react-boilerplate-dlls/'),
      include: path.join(process.cwd(), 'node_modules'),

    }),
  ],
  postcss: () =>  [
    postcssFocus(), // Add a :focus to every :hover
    cssnext({ // Allow future CSS features to be used, also auto-prefixes the CSS...
      browsers: ['last 2 versions', 'IE > 10'], // ...based on this browser list
    }),
    postcssReporter({ // Posts messages from plugins to the terminal
      clearMessages: true,
    }),
  ],
  resolve: {
    modules: ['app','server', 'node_modules'],
    extensions: [
      '',
      '.js',
      '.jsx',
      '.react.js',
      'css',
    ],
    packageMains: [
      'jsnext:main',
      'main',
    ],
  },

  target: 'node', // Make web variables accessible to webpack, e.g. window
  stats: true, // Don't show stats in the console
  progress: true,
};
```

If you look at ершы  boilerplate, you will see, that author imports `import 'sanitize.css/sanitize.css';`  in `app\containers\App\index.js`.  And I have an error with this line:

```
abbr[title] {
            ^
SyntaxError: Unexpected token {
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\sandbox\node\reactv12\build\server.js:106:25)
    at n (E:\sandbox\node\reactv12\build\server.js:1:177)
```

What I am doing wrong?

**Comment by dferber90** [comment]
~~You're disabling the loaders for `node_modules` with `exclude: /node_modules/,` and then you try to load from there.~~

**Comment by dferber90** [comment]
I see you're also using `include`, so I'm not sure. I don't know from the top of my head and would have to look into it myself extensively.

Closing this because it's not related to the fake-loaders themselves but rather a general webpack question.

**Comment by Stalso** [comment]
As you see, then I include node_modules and do not apply postCSS loader. In the next loader? after exclude


    {
        // Transform our own .css files with PostCSS and CSS-modules
        test: /\.css$/,
        exclude: /node_modules/,
        loader: 'fake-style-loader!css-loader?localIdentName=[local]__[path][name]__[hash:base64:5]&modules&importLoaders=1&sourceMap!postcss-loader',
      }, {

        test: /\.css$/,
        include: /node_modules/,
        loader: 'fake-style-loader!css-loader?modules',
      },

**Comment by Stalso** [comment]
If you will look at it, it will be cool. I am not webpack guru at all and in fact I almost gave up with this problem.

**Comment by dferber90** [comment]
See my second reply :P

Sorry, I'm not going to help you set up your Webpack config. I'm doing this at work a lot and I don't intend doing it in my free time. It's a lot of trial-and-error in the beginning, so just stick to it :)

There's a course about webpack on [egghead.io](https://egghead.io/courses/production-webpack-working-title). It's free this weekend, so maybe you can watch that. Haven't watched it myself but I think it's good.

**Comment by dferber90** [comment]
By the way.. You're trying to do two really hard things here:
- using webpack to bundle for the server
- adding postCSS to css modules

So don't get discouraged with Webpack if you can't do it. Getting this right is really hard.

**Comment by Stalso** [comment]
And there are no problems with css-modules)) The main problem is require css from node-modules (for expample `sanitize.css`) .

**Comment by dferber90** [comment]
Sorry, my previous answers were written in a rush.

_fake-style-loader_ only works with css-loader in modules mode. I don't think the `sanitize.css` file is a css module, so it breaks.

You most likely don't need to use fake-style-loader for regular css files. You can just serve them as usual. Hope this helps.

**Comment by Stalso** [comment]
Thank you
