### ISSUE TITLE
I think css-loader can handle what fake-style-loader is trying to achieve

### ISSUE THREAD

**Issue by chibicode** [dferber90/fake-style-loader#3]
I was able to do what `fake-style-loader` was trying to do w/ just `css-loader`, by invoking `css-loader/locals` instead of `style-loader!css-loader`. Take a look at the `css-loader` documentation:
https://github.com/webpack/css-loader

It says:

> Note: For prerendering with extract-text-webpack-plugin you should use c`ss-loader/locals` instead of `style-loader!css-loader` in the prerendering bundle. It doesn't embed CSS but only exports the identifier mappings.

They use the term "prerendering" but that apparently actually means "server side rendering." So I tried this on webpack for the **server side**:

``` js
// webpack.server.config.js
{
  test: /\.css$/,
  loader: 'css-loader/locals?modules&localIdentName=[path][name]---[local]---[hash:base64:5]'
}
```

`App.css`:

``` css
.foo {
  padding: 100px;
}
```

Then on a JS file:

``` js
import s from './App.css'

console.log(s)
```

Then I get this on the **server** console:

``` js
{ foo: '_-common-styles-App---foo---dA4q_' }
```

So that seems to do the job for me (I just need to use `extract-text-webpack-plugin`). The imported object doesn't contain `source` key like `fake-style-loader`, but I think this suffices. 

Maybe adding a note about this--that `css-loader` has a built-in way to do what `fake-style-loader` was trying to do--to the documentation might help?

**Comment by dferber90** [comment]
Thanks for finding this out and explaining it so well @chibicode, this is awesome! These features didn't exist when I first wrote this module.

Hope I can deprecate this module soon, like I did for [fake-file-loader](https://github.com/dferber90/fake-file-loader) and [fake-url-loader](https://github.com/dferber90/fake-url-loader) after `file-loader` and `url-loader` added the functionality themselves.

I'm unsure whether having access to the `source` is worth keeping this module non-deprecated. I'll update the README.

**Comment by dferber90** [comment]
I deprecated this module and linked to this issue from the README and the npm deprecation notice since it does such a good job of explaining how to upgrade. I also updated the article.

Thank you once again!

_If anyone is out there that was using the `source` feature of `fake-style-loader`, please let me know in this issue. I may un-deprecate `fake-style-loader` if there is interest._

**Comment by chibicode** [comment]
Thank you very much! @dferber90

**Comment by catamphetamine** [comment]
> The imported object doesn't contain source key like fake-style-loader, but I think this suffices.

No, it is not.
Why do you discriminate all those people not using CSS modules.
Racism.

> I'm unsure whether having access to the source is worth keeping this module non-deprecated.

Same

**Comment by dferber90** [comment]
Sorry, I don't get your comment. Can you explain?

**Comment by catamphetamine** [comment]
@dferber90 When CSS is used (not "css modules") then those "identifier mappings" aren't of any use. The original CSS is what's required.

**Comment by dferber90** [comment]
Could you not use a combination of other loaders to get that information?

**Comment by catamphetamine** [comment]
@dferber90 Maybe, I didn't check. Maybe `css-loader` returns the CSS. I guess it should.

**Comment by rogic89** [comment]
@chibicode  Worked great, thank you!
